### ISSUE TITLE
もっと見るボタン

### ISSUE THREAD

**Issue by lakk5688** [funswift/swift2021b#88]
## 概要
外観（画像１）
## 詳細
- もっと見るボタン（ボックスと同じサイズ）
- 押した後、タグのページに飛ぶ（空白のページ）

**Comment by Yuto5176** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/TeamB-6156926a2d6bfd0012aeb16c/issues/funswift/swift2021b/88?planning-poker) with ZenHub @azusa1120 @lakk5688 @Nagumo-7960 @yatoto
